### PR TITLE
Adds new field in Model "Category"

### PR DESCRIPTION
**Pull request by blackshot**
I did this because browsing models, loras, embeddings, etc... is a complete mess, it's just an improve to UX.

image
image
image
image

Feel free to edit categories before merging, i just want better filtering when im browsing

### CODE REVIEW

**Comment by JustMaier** [comment]
First off, wow, our first major contribution from the community ❤️
Thank you!

I agree with you about the categories of resources not being great. The labels that we have at the top of the page are very image centric and not very helpful when browsing resources. We're currently working on overhauling the browsing and filtering experience and were actually just talking about how we need to have different categories for each type of browsable thing (Models, images, etc), but we were struggling to decide what the categories should be. I really like the ones you came up with.

Let me figure out the right way to fit this into our overhaul that should be rolling out next week 👍
Ideally, we can do it in a way that won't require everyone to go set the categories for their old stuff.

**Comment by blackshot** [comment]
Thanks :) no problem, i won't feel bad if this isn't merged take your time 💪

**Comment by picobyte** [comment]
maybe for inspiration, f95zone has a nice search interface (requires login though) where you can add and/or exclude tags.

**Review by shamblessed — APPROVED** [review]
Newww

**Comment by manuelurenah** [comment]
Thank you @blackshot for taking the time to open this PR, since this is really outdated and we have make changes to UI drastically from what you first developed, I'll be closing this PR. Hopefully this issue has been resolved with the constant changes we have been delivering to the site.

**Pull request closed without merging**
